[workspace]
members = ["projects/*"]
default-members = [
    "projects/dejavu-parser",
    "projects/dejavu-bootstrap",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
