[package]
name = "dejavu-parser"
version = "0.0.0"
authors = ["192607617@qq.com"]
description = "Parser of DejaVu Language"
license = "MPL-2.0"
readme = "Readme.md"
repository = "https://github.com/doki-land/arc-rs"
documentation = "https://docs.rs/dejavu-parser"
exclude = ["/tests/*"]
edition = "2018"

[dependencies]
peginator = "0.6.0"
unicode-ident = "1.0.5"
ucd-trie = "0.1.5"

[dev-dependencies]

[build-dependencies]
peginator_codegen  = "0.6.0"

[features]
default = []

#json = ["serde_json", "serde_json/preserve_order"]
#yaml = ["yaml-rust"]
#hjson = ["serde-hjson"]